/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    '@debugFeedsMasonryAbs': typeof import('./src/components/@debug-feeds-masonry-abs.vue')['default']
    'About.detail': typeof import('./src/components/setting-widgets/about.detail.vue')['default']
    'About.update': typeof import('./src/components/setting-widgets/about.update.vue')['default']
    BlockPanel: typeof import('./src/components/block-panel.vue')['default']
    DialogWrapper: typeof import('./src/components/utils/dialog-wrapper.vue')['default']
    DropdownMenu: typeof import('./src/components/utils/dropdown-menu.vue')['default']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    FeedsMasonry: typeof import('./src/components/feeds-masonry.vue')['default']
    HeaderProgress: typeof import('./src/components/header-progress.vue')['default']
    ImagesViewer: typeof import('./src/components/images-viewer.vue')['default']
    'Layout.customBack': typeof import('./src/components/setting-widgets/layout.custom-back.vue')['default']
    MessageBox: typeof import('./src/components/utils/message-box.vue')['default']
    ModuleControl: typeof import('./src/components/@deprecated/module-control.vue')['default']
    NavBar: typeof import('./src/components/nav-bar.vue')['default']
    Pager: typeof import('./src/components/pager.vue')['default']
    Pages: typeof import('./src/components/pages/index.vue')['default']
    PostContainer: typeof import('./src/components/post-container.vue')['default']
    Settings: typeof import('./src/components/settings.vue')['default']
    'Theme.color': typeof import('./src/components/setting-widgets/theme.color.vue')['default']
    ThreadEditor: typeof import('./src/components/thread-editor.vue')['default']
    Toast: typeof import('./src/components/utils/toast.vue')['default']
    ToggleButton: typeof import('./src/components/utils/toggle-button.vue')['default']
    TogglePanel: typeof import('./src/components/toggle-panel.vue')['default']
    UserButton: typeof import('./src/components/utils/user-button.vue')['default']
    UserTextbox: typeof import('./src/components/utils/user-textbox.vue')['default']
  }
}
